In [1]:
!pip install duckdb
!pip install pandas
!pip install duckdb-engine jupysql
!pip install pathlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: duckdb in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.5.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: duckdb-engine in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.17.0)
Requirement already satisfied: jupysql in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.11.1)
Requirement already satisfied: duckdb>=0.5.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from duckdb-engine) (1.5.2)
Requirement already satisfied: packaging>=21 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from duckdb-engine) (26.1)
Requirement already satisfied: sqlalchemy>=1.3.22 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from duckdb-engine) (2.0.49)
Requirement already satisfied: prettytable>=3.12.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupysql) (3.17.0)
Requirement already satisfied: sqlparse in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupysql) (0.5.5)
Requirement already satisfied: ipython-genutils>=0.1.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupysql) (30.6.0)
Requirement already satisfied: jupysql-plugin>=0.4.2 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupysql) (0.4.5)
Requirement already satisfied: ploomber-core>=0.2.7 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jupysql) (0.2.27)
Requirement already satisfied: pyyaml in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Requirement already satisfied: posthog>=3.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from ploomber-core>=0.2.7->jupysql) (7.13.0)
Requirement already satisfied: requests<3.0,>=2.7 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.33.1)
Requirement already satisfied: python-dateutil>=2.2 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.9.0.post0)
Requirement already satisfied: backoff>=1.10.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: typing-extensions>=4.2.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2026.4.22)
Requirement already satisfied: wcwidth in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from prettytable>=3.12.0->jupysql) (0.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.2->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.17.0)
Requirement already satisfied: greenlet>=1 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy>=1.3.22->duckdb-engine) (3.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jinja2->jupysql) (3.0.3)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pathlib in C:\Users\Administrador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.0.1)

In [2]:
import duckdb
import pandas as pd 
from pathlib import Path

In [3]:
ROOT = Path().resolve().parent

con = duckdb.connect()
path_b = ROOT / "data" / "title.basics.tsv"
path_r = ROOT / "data" / "title.ratings.tsv"
path_w = ROOT / "data" / "watched.csv"
path_out = ROOT / "data" / "imdb_unseen.parquet"
path_out_user = ROOT / "data" / "user_profile.parquet"
path_demo = ROOT / "data" / "imdb_demo.parquet"

In [4]:
con.execute(f"""
    CREATE TABLE imdb AS
    SELECT 
        b.tconst,
        b.primaryTitle,
        b.originalTitle,
        b.startYear,
        b.runtimeMinutes,
        b.genres,
        r.averageRating,
        r.numVotes
    FROM read_csv('{path_b}', header=True, delim='\t', nullstr='\\N') b
    LEFT JOIN read_csv('{path_r}', header=True, delim='\t') r 
        ON b.tconst = r.tconst
    WHERE b.titleType = 'movie' AND b.isAdult = '0'
""")

In [5]:
con.execute("SELECT COUNT(*) FROM imdb").fetchone()

con.execute("""
    SELECT
        COUNT(*) AS total,
        COUNT(runtimeMinutes) AS com_duracao,
        COUNT(averageRating) as com_nota,
        COUNT(startYear) as com_ano
     FROM imdb
""").fetchdf()

    total  com_duracao  com_nota  com_ano
0  727550       459143    337864   617739

In [6]:
con.execute(f"""
    CREATE TABLE imdb_unseen AS
    SELECT i.*
    FROM imdb i
    LEFT JOIN read_csv('{path_w}', header=True, delim=',') w
        ON (
            LOWER(TRIM(i.primaryTitle)) = LOWER(TRIM(w.Name))
            OR
            LOWER(TRIM(i.originalTitle)) = LOWER(TRIM(w.Name))
            )
        AND TRY_CAST(i.startYear AS INTEGER) = w.Year
    WHERE w.Name IS NULL   
""")

In [7]:
con.execute("""
    SELECT       
        (SELECT COUNT(*) FROM imdb) AS total_imdb,
        (SELECT COUNT(*) FROM imdb_unseen) AS total_unseen
""").fetchdf()

   total_imdb  total_unseen
0      727550        727316

In [8]:
con.execute("""
    SELECT DISTINCT TRIM(genre) AS genre, COUNT(*) AS total
    FROM (
        SELECT UNNEST(STRING_SPLIT(genres,',')) AS genre
        FROM imdb_unseen
        WHERE genres IS NOT NULL
    )
    GROUP BY genre
    ORDER BY total DESC            
""").fetchdf()

          genre   total
0         Drama  268256
1   Documentary  145185
2        Comedy  121701
3        Action   60734
4       Romance   52680
5      Thriller   52145
6        Horror   45509
7         Crime   42307
8     Adventure   31391
9       Mystery   20057
10       Family   19742
11    Biography   19636
12      Fantasy   17721
13      History   16413
14       Sci-Fi   16097
15        Music   15095
16      Musical   11148
17    Animation   10969
18          War   10063
19        Sport    8734
20      Western    8029
21         News    1506
22    Film-Noir     877
23   Reality-TV     600
24    Talk-Show     214
25    Game-Show      34
26        Short       3
27        Adult       1

In [9]:
con.execute("""
    ALTER TABLE imdb_unseen
    ALTER COLUMN startYear TYPE INTEGER USING TRY_CAST(startYear AS INTEGER);
""")
con.execute("""
    ALTER TABLE imdb_unseen
    ALTER COLUMN runtimeMinutes TYPE INTEGER USING TRY_CAST(runtimeMinutes AS INTEGER);
""")

In [10]:
con.execute("""
    SELECT
        COUNT(*) AS total,
        COUNT(runtimeMinutes) AS com_duracao,
        COUNT(averageRating) as com_nota,
        MIN(startYear) as ano_min,
        MAX(startYear) as ano_max,
        ROUND(AVG(averageRating),2) as media_nota
    FROM imdb_unseen
""").fetchdf()

    total  com_duracao  com_nota  ano_min  ano_max  media_nota
0  727316       458910    337631     1894     2031        6.16

In [13]:
con.execute(f"""
    CREATE TABLE watched_data AS
    SELECT 
        TRIM(w.Name) AS Name,
        w.Year,
        c.startYear,
        c.runtimeMinutes,
        c.genres
    FROM read_csv('{path_w}', header=True, delim=',') w
    LEFT JOIN imdb c ON (
            LOWER(TRIM(c.primaryTitle)) = LOWER(TRIM(w.Name))
            OR
            LOWER(TRIM(c.originalTitle)) = LOWER(TRIM(w.Name))
            )
        AND TRY_CAST(c.startYear AS INTEGER) = w.Year
""")

In [17]:
con.execute("""
    CREATE OR REPLACE TABLE top_3_genres AS
    SELECT genre, count(*) as freq
    FROM (
        SELECT unnest(string_split(genres, ',')) as genre 
        FROM watched_data
    )
    GROUP BY 1 
    ORDER BY freq DESC 
    LIMIT 3;
""")

In [18]:
con.execute(f"""
    CREATE OR REPLACE TABLE user_metrics AS
    SELECT
        AVG(runtimeMinutes) AS avg_runtime,
        (SELECT list_aggregate(list(genre), 'string_agg', ', ') FROM top_3_genres) AS top_genres,
        (SELECT (CAST(startYear AS INTEGER) / 10) * 10 
            FROM watched_data 
            WHERE startYear IS NOT NULL
            GROUP BY 1 
            ORDER BY COUNT(*) DESC 
            LIMIT 1) AS top_decade
    FROM watched_data;
""")

con.execute(f"COPY user_metrics TO '{path_out_user}' (FORMAT PARQUET);")

In [ ]:
con.execute(f"""
    COPY (SELECT * FROM imdb_unseen) TO '{path_out}' (FORMAT 'parquet')
""")
print("Exportado com sucesso!")